// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOne4gBaZUUvXjqIMAf3LCXcO4P0ZeGN8',
    appId: '1:807046104354:web:4816e5cbb3f6251241d17b',
    messagingSenderId: '807046104354',
    projectId: 'personal-gallery-26f84',
    authDomain: 'personal-gallery-26f84.firebaseapp.com',
    storageBucket: 'personal-gallery-26f84.firebasestorage.app',
    measurementId: 'G-W36LV7L7Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbHtFhcvNgyAktO5phv5jY0i9Vjvefp0I',
    appId: '1:807046104354:android:c946d3b19cfed4e941d17b',
    messagingSenderId: '807046104354',
    projectId: 'personal-gallery-26f84',
    storageBucket: 'personal-gallery-26f84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlVhtUUqlZY8z5XVA0HyP6lZqzuPHmO8A',
    appId: '1:807046104354:ios:fcba3a0acef8734441d17b',
    messagingSenderId: '807046104354',
    projectId: 'personal-gallery-26f84',
    storageBucket: 'personal-gallery-26f84.firebasestorage.app',
    iosBundleId: 'com.example.gallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlVhtUUqlZY8z5XVA0HyP6lZqzuPHmO8A',
    appId: '1:807046104354:ios:fcba3a0acef8734441d17b',
    messagingSenderId: '807046104354',
    projectId: 'personal-gallery-26f84',
    storageBucket: 'personal-gallery-26f84.firebasestorage.app',
    iosBundleId: 'com.example.gallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOne4gBaZUUvXjqIMAf3LCXcO4P0ZeGN8',
    appId: '1:807046104354:web:7e95ce8c1767f46641d17b',
    messagingSenderId: '807046104354',
    projectId: 'personal-gallery-26f84',
    authDomain: 'personal-gallery-26f84.firebaseapp.com',
    storageBucket: 'personal-gallery-26f84.firebasestorage.app',
    measurementId: 'G-J0RM538GGF',
  );
}
